---
- hosts: all
  become: yes
  become_user: deploy
  vars:
    temp_repo_path: '/tmp/wallet-ui'
  tasks:
    - name: Clone the latest repo to tmp path
      git:
        repo: git@github.com:arcana-network/wallet-ui.git
        key_file: /home/deploy/.ssh/wallet-ui/id_rsa
        accept_hostkey: yes
        dest: '{{ temp_repo_path }}'
        version: '{{branch}}'
      register: code_upload

    - name: Change the permissions of folders
      shell: 'sudo chown deploy:tesla -R /tmp/wallet-ui/'

    - name: Rsync the code to our running repo
      delegate_to: '{{ inventory_hostname }}'
      synchronize:
        src: /tmp/wallet-ui/
        dest: /home/deploy/wallet-ui/
        rsync_opts:
          - '--exclude=.env'
          - '--exclude=.npmrc'
        delete: yes
        recursive: yes
      when: code_upload.changed

    - name: Change the permissions of folders
      shell: 'sudo chown deploy:deploy -R /tmp/wallet-ui'

    - name: Install npm dependencies
      shell: |
        source /home/deploy/.profile
        cd /home/deploy/wallet-ui/ && npm install
      args:
        executable: /bin/bash

    - name: Build the project
      shell: |
        cd /home/deploy/wallet-ui/ && npm run build
      args:
        executable: /bin/bash

    - name: Rsync build files to the production folder
      shell: |
        rsync -av --delete /home/deploy/wallet-ui/ /home/deploy/wallet-ui-files/
      args:
        executable: /bin/bash

    - name: Remove the tmp cloned repo
      file:
        path: '{{ temp_repo_path }}'
        state: absent
